export const chartData = [
  {
    name: 'Jan',
    categories: {
      Commercial: {
        costSavings: 12000,
        volume: 300,
        claims: 24,
        members: 150,
        value: 10,
      },
      Medicare: {
        costSavings: 8000,
        volume: 200,
        claims: 18,
        members: 120,
        value: 6,
      },
      Medicaid: {
        costSavings: 5000,
        volume: 100,
        claims: 12,
        members: 75,
        value: 4,
      },
      IFP: {
        costSavings: 6000,
        volume: 150,
        claims: 15,
        members: 100,
        value: 5,
      },
    },
  },
  {
    name: 'Feb',
    categories: {
      Commercial: {
        costSavings: 13000,
        volume: 320,
        claims: 28,
        members: 160,
        value: 12,
      },
      Medicare: {
        costSavings: 8500,
        volume: 180,
        claims: 20,
        members: 110,
        value: 5,
      },
      Medicaid: {
        costSavings: 5200,
        volume: 110,
        claims: 14,
        members: 80,
        value: 4,
      },
      IFP: {
        costSavings: 6500,
        volume: 170,
        claims: 18,
        members: 105,
        value: 5,
      },
    },
  },
  {
    name: 'Mar',
    categories: {
      Commercial: {
        costSavings: 11000,
        volume: 280,
        claims: 22,
        members: 140,
        value: 9,
      },
      Medicare: {
        costSavings: 7500,
        volume: 190,
        claims: 17,
        members: 115,
        value: 5,
      },
      Medicaid: {
        costSavings: 4700,
        volume: 90,
        claims: 11,
        members: 70,
        value: 3,
      },
      IFP: {
        costSavings: 6200,
        volume: 160,
        claims: 16,
        members: 95,
        value: 5,
      },
    },
  },
  {
    name: 'Apr',
    categories: {
      Commercial: {
        costSavings: 13500,
        volume: 340,
        claims: 30,
        members: 170,
        value: 13,
      },
      Medicare: {
        costSavings: 8700,
        volume: 210,
        claims: 22,
        members: 125,
        value: 6,
      },
      Medicaid: {
        costSavings: 5400,
        volume: 120,
        claims: 15,
        members: 85,
        value: 4,
      },
      IFP: {
        costSavings: 6700,
        volume: 180,
        claims: 19,
        members: 110,
        value: 5,
      },
    },
  },
  {
    name: 'May',
    categories: {
      Commercial: {
        costSavings: 12500,
        volume: 310,
        claims: 25,
        members: 155,
        value: 11,
      },
      Medicare: {
        costSavings: 8200,
        volume: 200,
        claims: 19,
        members: 120,
        value: 5,
      },
      Medicaid: {
        costSavings: 5100,
        volume: 105,
        claims: 13,
        members: 77,
        value: 4,
      },
      IFP: {
        costSavings: 6400,
        volume: 165,
        claims: 17,
        members: 100,
        value: 5,
      },
    },
  },
  {
    name: 'Jun',
    categories: {
      Commercial: {
        costSavings: 14000,
        volume: 350,
        claims: 32,
        members: 180,
        value: 14,
      },
      Medicare: {
        costSavings: 8800,
        volume: 220,
        claims: 23,
        members: 130,
        value: 6,
      },
      Medicaid: {
        costSavings: 5500,
        volume: 130,
        claims: 16,
        members: 90,
        value: 4,
      },
      IFP: {
        costSavings: 6800,
        volume: 190,
        claims: 20,
        members: 115,
        value: 5,
      },
    },
  },
  {
    name: 'Jul',
    categories: {
      Commercial: {
        costSavings: 11500,
        volume: 270,
        claims: 21,
        members: 135,
        value: 8,
      },
      Medicare: {
        costSavings: 7300,
        volume: 170,
        claims: 16,
        members: 105,
        value: 5,
      },
      Medicaid: {
        costSavings: 4600,
        volume: 85,
        claims: 10,
        members: 60,
        value: 3,
      },
      IFP: {
        costSavings: 6100,
        volume: 150,
        claims: 14,
        members: 90,
        value: 5,
      },
    },
  },
  {
    name: 'Aug',
    categories: {
      Commercial: {
        costSavings: 14500,
        volume: 360,
        claims: 35,
        members: 190,
        value: 15,
      },
      Medicare: {
        costSavings: 9100,
        volume: 230,
        claims: 25,
        members: 140,
        value: 7,
      },
      Medicaid: {
        costSavings: 5700,
        volume: 140,
        claims: 18,
        members: 95,
        value: 5,
      },
      IFP: {
        costSavings: 6900,
        volume: 200,
        claims: 22,
        members: 120,
        value: 6,
      },
    },
  },
  {
    name: 'Sep',
    categories: {
      Commercial: {
        costSavings: 13000,
        volume: 320,
        claims: 28,
        members: 160,
        value: 12,
      },
      Medicare: {
        costSavings: 8600,
        volume: 210,
        claims: 21,
        members: 130,
        value: 6,
      },
      Medicaid: {
        costSavings: 5300,
        volume: 115,
        claims: 14,
        members: 80,
        value: 4,
      },
      IFP: {
        costSavings: 6600,
        volume: 180,
        claims: 19,
        members: 110,
        value: 5,
      },
    },
  },
  {
    name: 'Oct',
    categories: {
      Commercial: {
        costSavings: 12000,
        volume: 310,
        claims: 26,
        members: 150,
        value: 11,
      },
      Medicare: {
        costSavings: 8000,
        volume: 180,
        claims: 17,
        members: 110,
        value: 5,
      },
      Medicaid: {
        costSavings: 5000,
        volume: 100,
        claims: 12,
        members: 75,
        value: 5,
      },
      IFP: {
        costSavings: 6300,
        volume: 160,
        claims: 16,
        members: 95,
        value: 5,
      },
    },
  },
  {
    name: 'Nov',
    categories: {
      Commercial: {
        costSavings: 13500,
        volume: 330,
        claims: 30,
        members: 170,
        value: 13,
      },
      Medicare: {
        costSavings: 8800,
        volume: 200,
        claims: 19,
        members: 120,
        value: 6,
      },
      Medicaid: {
        costSavings: 5400,
        volume: 110,
        claims: 13,
        members: 80,
        value: 4,
      },
      IFP: {
        costSavings: 6700,
        volume: 170,
        claims: 18,
        members: 105,
        value: 5,
      },
    },
  },
  {
    name: 'Dec',
    categories: {
      Commercial: {
        costSavings: 12500,
        volume: 300,
        claims: 25,
        members: 160,
        value: 12,
      },
      Medicare: {
        costSavings: 8300,
        volume: 190,
        claims: 18,
        members: 115,
        value: 5,
      },
      Medicaid: {
        costSavings: 5100,
        volume: 95,
        claims: 11,
        members: 70,
        value: 4,
      },
      IFP: {
        costSavings: 6400,
        volume: 160,
        claims: 17,
        members: 100,
        value: 5,
      },
    },
  },
];
